DEFAULT_BASE_URL = "https://webexapis.com/v1/"

DEFAULT_SINGLE_REQUEST_TIMEOUT = 60

DEFAULT_WAIT_ON_RATE_LIMIT = True

ACCESS_TOKEN_ENVIRONMENT_VARIABLE = "WEBEX_ACCESS_TOKEN"

LEGACY_ACCESS_TOKEN_ENVIRONMENT_VARIABLES = [
    "SPARK_ACCESS_TOKEN",
    "CISCO_SPARK_ACCESS_TOKEN",
    "WEBEX_TEAMS_ACCESS_TOKEN",
]

WEBEX_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
