line-length = 120
exclude = [".venv"]
fix = false
respect-gitignore = true

[format]
docstring-code-format = true
docstring-code-line-length = 120
indent-style = "space"
# Use `\n` line endings for all files
line-ending = "lf"
quote-style = "double"

[lint]
ignore = ["ANN101", "ANN204", "ANN002", "ANN102", "ANN003", "E501"]
select = ["E", "F", "B", "Q", "D101", "D102", "D103", "N", "ANN"]

[lint.flake8-type-checking]
strict = true

[lint.flake8-unused-arguments]
ignore-variadic-names = true